<?php

namespace Module\Cp_SupplierShippingTime\Command;

interface EditSupplierShippingTimeCommandInterface extends SupplierShippingTimeCommandInterface, SupplierShippingTimeIdentifierCommandInterface
{
}
