services:
  _defaults:
    public: true

  # Grid
  cp_suppliershippingtime.grid.definition.factory:
    class: 'Module\Cp_SupplierShippingTime\Grid\Definition\Factory\SupplierShippingTimeDefinitionFactory'
    parent: "prestashop.core.grid.definition.factory.abstract_grid_definition"
    public: true

  cp_suppliershippingtime.grid.query_builder:
    class: 'Module\Cp_SupplierShippingTime\Grid\Query\SupplierShippingTimeQueryBuilder'
    parent: "prestashop.core.grid.abstract_query_builder"
    public: true
    arguments:
      - "@prestashop.core.query.doctrine_search_criteria_applicator"
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - "@prestashop.core.grid.query.filter.doctrine_filter_applicator"

  cp_suppliershippingtime.grid.data.factory:
    class: "%prestashop.core.grid.data.factory.doctrine_grid_data_factory%"
    arguments:
      - "@cp_suppliershippingtime.grid.query_builder"
      - "@prestashop.core.hook.dispatcher"
      - "@prestashop.core.grid.query.doctrine_query_parser"
      - "SupplierShippingTime"

  cp_suppliershippingtime.grid.data.factory.decorator:
    class: 'Module\Cp_SupplierShippingTime\Grid\Data\Factory\SupplierShippingTimeDataFactory'
    arguments:
      - '@cp_suppliershippingtime.grid.data.factory'

  cp_suppliershippingtime.grid.grid_factory:
    class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
    arguments:
      - '@cp_suppliershippingtime.grid.definition.factory'
      - '@cp_suppliershippingtime.grid.data.factory.decorator'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
  
  # Form
  cp_suppliershippingtime.type.supplier_shipping_time:
    class: 'Module\Cp_SupplierShippingTime\Form\Type\SupplierShippingTimeType'
    parent: 'form.type.translatable.aware'
    public: true
    arguments: 
      - '@cp_suppliershippingtime.repository.supplier_shipping_time_repository'
    tags:
      - { name: form.type }

  cp_suppliershippingtime.form.identifiable.object.builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'Module\Cp_SupplierShippingTime\Form\Type\SupplierShippingTimeType'
      - '@cp_suppliershippingtime.form.identifiable_object.data.provider'

  cp_suppliershippingtime.form.identifiable_object.data.provider:
    class: 'Module\Cp_SupplierShippingTime\Form\Provider\SupplierShippingTimeFormDataProvider'    
    arguments: 
      - '@cp_suppliershippingtime.repository.supplier_shipping_time_repository'

  # Form Handler
  cp_suppliershippingtime.command.builder.supplier_shipping_time:
    class: 'Module\Cp_SupplierShippingTime\CommandBuilder\SupplierShippingTimeCommandBuilder'

  cp_suppliershippingtime.form.identifiable.object.data.handler:
    class: 'Module\Cp_SupplierShippingTime\Form\DataHandler\SupplierShippingTimeFormDataHandler'
    arguments:
      - '@prestashop.core.command_bus'
      - '@cp_suppliershippingtime.command.builder.supplier_shipping_time'

  cp_suppliershippingtime.form.identifiable.object.handler:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Handler\FormHandler'
    factory: 'prestashop.core.form.identifiable_object.handler.form_handler_factory:create'
    arguments:
      - '@cp_suppliershippingtime.form.identifiable.object.data.handler'

  cp_suppliershippingtime.command.handler.add_supplier_shipping_time:
    class: 'Module\Cp_SupplierShippingTime\CommandHandler\AddSupplierShippingTimeCommandHandler'
    arguments:
      - '@prestashop.core.admin.lang.repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'tactician.handler', command: 'Module\Cp_SupplierShippingTime\Command\AddSupplierShippingTimeCommand' }

  cp_suppliershippingtime.command.handler.edit_supplier_shipping_time:
    class: 'Module\Cp_SupplierShippingTime\CommandHandler\EditSupplierShippingTimeCommandHandler'
    arguments:
      - '@prestashop.core.admin.lang.repository'
      - '@cp_suppliershippingtime.repository.supplier_shipping_time_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'tactician.handler', command: 'Module\Cp_SupplierShippingTime\Command\EditSupplierShippingTimeCommand' }

  cp_suppliershippingtime.command.handler.delete_supplier_shipping_time:
    class: 'Module\Cp_SupplierShippingTime\CommandHandler\DeleteSupplierShippingTimeCommandHandler'
    arguments:
      - '@cp_suppliershippingtime.repository.supplier_shipping_time_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'tactician.handler', command: 'Module\Cp_SupplierShippingTime\Command\DeleteSupplierShippingTimeCommand' }

  cp_suppliershippingtime.command.handler.bulk_delete_supplier_shipping_time:
    class: 'Module\Cp_SupplierShippingTime\CommandHandler\BulkDeleteSupplierShippingTimeCommandHandler'
    arguments:
      - '@cp_suppliershippingtime.repository.supplier_shipping_time_repository'
      - '@doctrine.orm.default_entity_manager'
    tags:
      - { name: 'tactician.handler', command: 'Module\Cp_SupplierShippingTime\Command\BulkDeleteSupplierShippingTimeCommand' }

  # Repository
  cp_suppliershippingtime.repository.supplier_shipping_time_repository:
    class: 'Module\Cp_SupplierShippingTime\Repository\SupplierShippingTimeRepository'
    factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
    arguments:
      - 'Module\Cp_SupplierShippingTime\Entity\SupplierShippingTime'